In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

plt.rcParams.update({ 
    "text.usetex": True,
    "font.family": "Times New Roman",
    "font.size": 16
})

from matplotlib.ticker import MultipleLocator, AutoMinorLocator

In [16]:
csv_directory = "./visualization/error_bar/"

DR_nostd_df = pd.read_csv(csv_directory + "DR_omega_nostandard_IHDP.csv")
DR_std_df = pd.read_csv(csv_directory + "DR_omega_standard_IHDP.csv")

In [ ]:
# DR_nostd_df

    OMEGA_CONF   ATE_hat  |ATE_err|  sqrt_PEHE  sqrt_PEHE_CIhalf    ITE_R2
0         0.00  4.050712   0.046745   1.484080          0.129285 -2.556325
1         0.05  4.050085   0.046117   1.470794          0.123326 -2.492939
2         0.10  4.049572   0.045605   1.459757          0.118483 -2.440712
3         0.15  4.049156   0.045189   1.450610          0.114530 -2.397724
4         0.20  4.048822   0.044854   1.443083          0.111304 -2.362556
5         0.25  4.048558   0.044590   1.436976          0.108684 -2.334157
6         0.30  4.048357   0.044389   1.432139          0.106582 -2.311749
7         0.35  4.048213   0.044245   1.428461          0.104932 -2.294762
8         0.40  4.048123   0.044155   1.425865          0.103688 -2.282794
9         0.45  4.048085   0.044118   1.424298          0.102819 -2.275585
10        0.50  4.048100   0.044132   1.423735          0.102305 -2.272996
11        0.55  4.048169   0.044201   1.424173          0.102138 -2.275008
12        0.60  4.048296   0.044328   1.425631          0.102321 -2.281716
13        0.65  4.048488   0.044520   1.428154          0.102867 -2.293344
14        0.70  4.048753   0.044786   1.431818          0.103801 -2.310263
15        0.75  4.049106   0.045139   1.436732          0.105160 -2.333024
16        0.80  4.049565   0.045597   1.443052          0.107001 -2.362414
17        0.85  4.050155   0.046187   1.450999          0.109402 -2.399546
18        0.90  4.050914   0.046946   1.460880          0.112473 -2.446007
19        0.95  4.051897   0.047929   1.473144          0.116373 -2.504107
20        1.00  4.053187   0.049220   1.488460          0.121340 -2.577349

In [ ]:
# DR_std_df

    OMEGA_CONF   ATE_hat  |ATE_err|  sqrt_PEHE  sqrt_PEHE_CIhalf    ITE_R2
0         0.00  4.048309   0.044342   1.488888          0.133280 -2.579405
1         0.05  4.047888   0.043920   1.473386          0.126441 -2.505257
2         0.10  4.047546   0.043578   1.460537          0.120798 -2.444387
3         0.15  4.047271   0.043304   1.449897          0.116117 -2.394387
4         0.20  4.047055   0.043087   1.441138          0.112229 -2.353497
5         0.25  4.046890   0.042922   1.434013          0.109008 -2.320421
6         0.30  4.046772   0.042804   1.428341          0.106359 -2.294206
7         0.35  4.046698   0.042730   1.423988          0.104212 -2.274159
8         0.40  4.046667   0.042700   1.420862          0.102520 -2.259801
9         0.45  4.046680   0.042712   1.418904          0.101248 -2.250822
10        0.50  4.046738   0.042770   1.418086          0.100379 -2.247072
11        0.55  4.046845   0.042877   1.418408          0.099908 -2.248548
12        0.60  4.047006   0.043038   1.419903          0.099848 -2.255399
13        0.65  4.047230   0.043262   1.422636          0.100224 -2.267943
14        0.70  4.047529   0.043561   1.426712          0.101084 -2.286697
15        0.75  4.047918   0.043950   1.432287          0.102496 -2.312433
16        0.80  4.048420   0.044453   1.439582          0.104564 -2.346262
17        0.85  4.049069   0.045101   1.448912          0.107432 -2.389774
18        0.90  4.049911   0.045943   1.460726          0.111307 -2.445278
19        0.95  4.051018   0.047051   1.475686          0.116490 -2.516212
20        1.00  4.052504   0.048537   1.494810          0.123430 -2.607937

In [ ]:
plt.figure(figsize=(10,6))
plt.errorbar(DR_nostd_df['OMEGA_CONF'], 
             DR_nostd_df['sqrt_PEHE'], 
             yerr=DR_nostd_df['sqrt_PEHE_CIhalf'], 
             fmt='-o', capsize=4, color='#A8363A', label='No Standardization')
plt.errorbar(DR_std_df['OMEGA_CONF'], 
             DR_std_df['sqrt_PEHE'], 
             yerr=DR_std_df['sqrt_PEHE_CIhalf'], 
             fmt='-o', capsize=4, color='#2369BC', label='Standardization')
plt.xlabel("$\omega$")
plt.ylabel("$\sqrt{\epsilon_{PEHE}}$")
# plt.title("sqrt_PEHE vs OMEGA_CONF")
plt.legend()
# plt.grid(True)

# 隐去上边和右边的刻度
plt.tick_params(axis='x', which='both', top=False)
plt.tick_params(axis='y', which='both', right=False)

# 隐去次刻度
# plt.tick_params(axis='x', which='minor', bottom=False, top=False)
plt.tick_params(axis='y', which='minor', left=False, right=False)

# 设置主刻度间隔为4, 设置次刻度间隔为1
plt.gca().xaxis.set_major_locator(MultipleLocator(0.2))
plt.gca().xaxis.set_minor_locator(MultipleLocator(0.05))

plt.annotate(r'\textbf{(a)}', xy=(0, 0), xycoords='axes fraction',
    xytext=(-0.05, 1), textcoords='axes fraction',
    fontsize=22, ha='right', va='top')
# plt.title(r"BNN-NCC", fontsize=12)


plt.savefig(f'./visualization/error_bar/DR_diff_omega_PEHE.pdf', dpi=600, bbox_inches='tight')

plt.show()

In [ ]:
plt.figure(figsize=(10,6))
plt.plot(DR_nostd_df['OMEGA_CONF'], 
         DR_nostd_df['|ATE_err|'], 
         '-o', color='#A8363A', label='No Standardization')
plt.plot(DR_std_df['OMEGA_CONF'], 
         DR_std_df['|ATE_err|'], 
         '-o', color='#2369BC', label='Standardization')
plt.xlabel("$\omega$")
plt.ylabel("$\epsilon_{ATE}$")
# plt.title("|ATE_err| vs OMEGA_CONF")
plt.legend()
# plt.grid(True)

# plt.tick_params(axis='both', which='both', length=0)  # 去除刻度，但保留刻度标签

# 隐去上边和右边的刻度
plt.tick_params(axis='x', which='both', top=False)
plt.tick_params(axis='y', which='both', right=False)

# 隐去次刻度
# plt.tick_params(axis='x', which='minor', bottom=False, top=False)
plt.tick_params(axis='y', which='minor', left=False, right=False)

# 设置主刻度间隔为4, 设置次刻度间隔为1
plt.gca().xaxis.set_major_locator(MultipleLocator(0.2))
plt.gca().xaxis.set_minor_locator(MultipleLocator(0.05))

plt.annotate(r'\textbf{(b)}', xy=(0, 0), xycoords='axes fraction',
    xytext=(-0.05, 1), textcoords='axes fraction',
    fontsize=22, ha='right', va='top')
# plt.title(r"BNN-NCC", fontsize=12)

plt.savefig(f'./visualization/error_bar/DR_diff_omega_ATE.pdf', dpi=600, bbox_inches='tight')

plt.show()